adaptive_threshold:
  fixed_threshold: null
  initial_threshold: 2.0
  min_motion_th: 0.1
data:
  deskew: true
  max_range: 150.0
  min_range: 3.0
mapping:
  desired_num_voxelized_points: 3000
  map_cleanup_radius: 100.0
  max_points_per_voxel: 20
  planarity_threshold: 0.18
  voxel_size: 1.0
out_dir: ./results/baseline/mulran
registration:
  convergence_criterion: 0.0001
  max_num_iterations: 100
  max_num_threads: 0
